# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0645a31f04b4cd87f429fa371a3a844356b69d30a5ced4bfe1746a9038f5de41e6b254e6e41c7d376c6d1288514d24347dbd5717a9a21a6a03599e2ab4706fb0

test:
  secret_key_base: c3722caaa23250652b8b00f5e1f7fb635b1f058e285befec85e7dbd83c2d4df707ecd7f3929e2b7e22a447243abd6bc953701ced88c58bc0d0a8f99df6eb548d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
